name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET: ${{secrets.COMMIT_SECRET}}
      USER_NAME: wowdacom
      USER_EMAIL: wowdacom@gmail.com
      PUBLISH_DIR: ./dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build
      - name: Deploy
        run: |
          cd $PUBLISH_DIR
          git init
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL
          git status
          git remote add origin https://github.com/wowdacom/none-chinese-a-year.git
          npm run deploy
