name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET: ${{ secrets.COMMIT_SECRET }}
      USER_NAME: wowdacom
      USER_EMAIL: wowdacom@gmail.com
      PUBLISH_DIR: ./dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build
      - name: Deploy
        run: |
          cd $PUBLISH_DIR
          git init
          git config --global user.name wowdacom
          git config --global user.email wowdacom@gmail.com
          git status
          git remote add origin https://${{ USER_NAME }}:${{ secrets.COMMIT_SECRET }}@github.com/${{ USER_NAME }}/curious-mind-site.git
          git checkout -b gh-pages
          git add --all
          git commit -m "deploy to Github pages"
          git push origin gh-pages -f
          echo 🤘 deploy gh-pages complete.
